name: api_client
description: Client for the Compass API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
