name: compass_app
description: Another app that helps users build and book itineraries for trips.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  activity_repository:
    path: packages/activity_repository
  api_client:
    path: packages/api_client
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.3
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
